### ISSUE TITLE
PECSM-TEAM 2.2.2 has a file upload vulnerability in /Public/?g=Team&m=Setting&a=upgrade

### ISSUE THREAD

**Issue by snappyJack** [lazyphp/PESCMS-TEAM#2]
This page let user upgrade the PESCMS system manually.
![default](https://user-images.githubusercontent.com/16055573/44842488-94f5f480-ac78-11e8-8132-a54ffdca984d.png)

Follow the mtUpgrade funtction,the upload file extension must be “zip”
![default](https://user-images.githubusercontent.com/16055573/44842510-a2ab7a00-ac78-11e8-9b73-9ccf6b55d777.png)

and follow the unzip function
![default](https://user-images.githubusercontent.com/16055573/44842523-b060ff80-ac78-11e8-9b8b-e49aaf904bf7.png)

Follow the simulateInstall function and install function,we can see the file decompression in root directory
![default](https://user-images.githubusercontent.com/16055573/44842528-b7880d80-ac78-11e8-945e-6e0e532495d9.png)
![default](https://user-images.githubusercontent.com/16055573/44842535-bbb42b00-ac78-11e8-86bb-cad2174cfed6.png)

so,we can create a evil.php
![default](https://user-images.githubusercontent.com/16055573/44842546-c1117580-ac78-11e8-8b73-c910e3baa9ba.png)

and compression it as evil.zip,and upload the evil.zip,
![default](https://user-images.githubusercontent.com/16055573/44842547-c79fed00-ac78-11e8-9841-203852eb11d1.png)

at last ,the system decompress evil.zip and evil.php in root directory.
![default](https://user-images.githubusercontent.com/16055573/44842560-ce2e6480-ac78-11e8-9dcf-002ba225ac44.png)

**Comment by lazyphp** [comment]
英语水平有限，这里用中文吧：
因为考虑到程序都是内网为主，所以手动更新的程序并没有与官方进行 哈希验证。所以确实会存在一个提权的风险。目前这些各项功能还在调优中，不久将来的版本更新功能将需要与官方的更新包进行哈希验证，匹配正确才会执行更新。

**Comment by lazyphp** [comment]
即将发布的新版已经接近此问题。https://github.com/lazyphp/PESCMS-TEAM/tree/dev-2.3.0
